# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/setup-java@v3
      name: Setup java 17
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Cache maven
      id: cache-maven
      uses: actions/cache@v3
      with:
        path: ~/.maven
        key: ${{ runner.os }}-maven
          
    - uses: actions/checkout@v3
    
    - run: mvn --batch-mode --update-snapshots verify
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: "**/target"
  
  release:
    needs: [build]
    runs-on: ubuntu-18.04
    
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
        
      - name: Cache maven
        id: cache-maven
        uses: actions/cache@v3
        with:
          path: ~/.maven
          key: ${{ runner.os }}-maven

      - uses: actions/checkout@v3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_URL: "https://api.github.com/"
        run: npx --legacy-peer-deps -p @semantic-release/changelog -p @semantic-release/git -p @semantic-release/exec -p semantic-release-maven -p semantic-release semantic-release

